#!/usr/bin/perl

use warnings;
use strict;

use lib '../lib';
use WebGB;
use CGI qw(:standard);

my $q = new CGI;
my $sampleFile =  $WebGB::WWW . '/files/volvox.conf'; 
open SAMPLE, "<", $sampleFile or die "Can not open the specified file";
my @sampleContent = <SAMPLE>;
close SAMPLE;
print "Content-Type:text/x-download\n";
print "Content-Disposition:attachment;filename=volvox.conf\n\n";
print @sampleContent;
exit(0);

