#!/usr/bin/perl -w
use strict;
use warnings;
use YAML;

my $usage = "$0 <newGlyphYAMLFile>";

my $newGlyphYAMLFile = shift;;

unless ($newGlyphYAMLFile) {
	print "SYNTAX ERROR\n$usage\n";
	exit 1;
}

my %newGlyph = ();

# This data structure would hold the commplete structure of the new glyph.
# Most of the keys are based on HTML::FormEngine specification, populate the data structure with appropriate values.
# Insert the output generated by this file at the end of the Glyph Library YAML file (files/yamlib/glyphLibrary.yml).

$newGlyph{'Glyph Name'} = [
          {
            'glyph' => 'Glyph Name',
            'glyph_desc' => 'Glyph Description',
            'TITLE' => 'Glyph Parameters Form Title',
            'sub' => [
                       { # Repeat this block for each glyph parameter
                         'CONF_TAG' => 'Param Name',
                         'ERROR' => [
                                      'not_null'
                                    ],
                         'HINT' => 'Param Hint',
                         'LABEL' => 'HTML ID for the Form Field',
                         'MAXLEN' => '60',
                         'NAME' => 'HTML Name for the Form Field',
                         'REQUIRED' => '1',
                         'SIZE' => '60',
                         'TIP' => 'Param Tip',
                         'TITLE' => 'Param Prompt',
                         'VALUE' => ''
                       }
                     ],
            'templ' => 'fieldset',
          },
          {
            'JSHIDE' => 'advanced', # Parameters defined in this section will be displayed in the "Advanced Section" for the form which is by default in collapsed state
            'TITLE' => 'Advanced Section',
            'sub' => [
                       {
                         'CONF_TAG' => 'Param Name',
                         'ERROR' => [
                                      'not_null'
                                    ],
                         'HINT' => 'Param Hint',
                         'LABEL' => 'HTML ID for the Form Field',
                         'MAXLEN' => '60',
                         'NAME' => 'HTML Name for the Form Field',
                         'REQUIRED' => '1',
                         'SIZE' => '60',
                         'TIP' => 'Param Tip',
                         'TITLE' => 'Param Prompt',
                         'VALUE' => ''
                       }
                     ],
            'templ' => 'fieldset'
          }
        ];

my $yml = YAML::Dump(%newGlyph);
open (FILE, '>', $newGlyphYAMLFile) or die $!;
print FILE $yml;
close FILE;
print "Done\n";
