#!/usr/bin/perl
use warnings;
use strict;

use lib '../lib';
use CGI qw(:standard);
use WebGB;
use WebGB::GeneralData;
use WebGB::TrackData;
use WebGB::FormEngine;
use WebGB::FormEngine::SkinUniform;
use Clone qw(clone);

my $q = new CGI;
my ($timeStampDigest, $uploadDirectory, $uploadRoot) = ($q->url_param('tsd'), '', $WebGB::TMP);
if ($timeStampDigest eq '') {
	print $q->redirect(
		-location => '/'
	);
	exit(0);
}
$uploadDirectory = $uploadRoot . '/' . $timeStampDigest;
unless (-d $uploadDirectory) { 
	print $q-> redirect( 
		-location => '/'
	); 
	exit(0); 
}

my $yamlib = $WebGB::YAML_LIB;
my ($inputProfileFile, $featureSetFile, $generalSettingsFile, $trackConfigurationFile, $glyphLibraryFile) = ('inputProfile.yml', 'featureSet.yml', 'generalSettings.yml', 'trackConfiguration.yml', 'glyphLibrary.yml');
my $generalData = WebGB::GeneralData->new("$uploadDirectory/$generalSettingsFile");
my $trackData = WebGB::TrackData->new("$uploadDirectory/$featureSetFile", "$yamlib/$glyphLibraryFile", "$uploadDirectory/$trackConfigurationFile");
my %trackConfigurationData = $trackData->getTrackConfiguration;
my @confGlyph = @{$trackConfigurationData{'Tracks'}{$trackConfigurationData{'ActiveTrack'}}{'glyph'}};
my @cloneConfGlyph = @{clone(\@confGlyph)};

my $Form = WebGB::FormEngine->new(scalar $q->Vars);
$Form->set_skin_obj('WebGB::FormEngine::SkinUniform');
$Form->conf(\@cloneConfGlyph);
$Form->make();
if($Form->ok){
	$Form->clear();
	$trackData->resetEditMode;
	foreach (@confGlyph) {
		foreach (@{$_->{'sub'}}) {
			$_->{'VALUE'} = $q->param($_->{'NAME'});
		}
	}
	$trackData->saveTrackConfigurationToFile("$uploadDirectory/$trackConfigurationFile");
	print $q->redirect(
		-location => "/cgi-bin/configureTracks?tsd=$timeStampDigest"
	);
	exit(0);
}
if ($Form->canceled) {
	#my %trackConfigurationData = $trackData->getTrackConfiguration;
	$trackData->deleteTrack($trackConfigurationData{'ActiveTrack'}) if ($trackConfigurationData{'EditMode'} eq 'Add');
	$trackData->resetEditMode;
	$trackData->saveTrackConfigurationToFile("$uploadDirectory/$trackConfigurationFile");
	print $q->redirect(
		-location => "/cgi-bin/configureTracks?tsd=$timeStampDigest"
	);
	exit(0);
}

my $addLabel = 'Add Track';
my $editLabel = 'Edit Track';
my $deleteLabel = 'Delete Track';
my $doneLabel = 'Display in GBrowse';
my $saveLabel = 'Save Progress';

my ($paramDescription, $paramFeature, $paramGlyph, $paramTrack, $paramPostBackCommand) = ('txtDescription', 'lstFeature', 'lstGlyph', 'lstTrack', 'cmdSubmit');
my ($description, $feature, $glyph, $track) = ('', '', 'generic', '');
$description = $generalData->getDescription;

my %curTrack = %{${$trackConfigurationData{'Tracks'}}{$trackConfigurationData{'ActiveTrack'}}};

if ($trackConfigurationData{'EditMode'} eq 'Add') {
	$feature = $curTrack{'feature'};
	$glyph = ${${$curTrack{'glyph'}}[0]}{'glyph'};
}

if ($trackConfigurationData{'EditMode'} eq 'Edit') {
	$track = $trackConfigurationData{'ActiveTrack'};
}

my @features = $trackData->getFeatureList;
my @glyphs = $trackData->getGlyphList;
my %tracks = $trackData->getTracks;
#my %trackConfigurationData = $trackData->getTrackConfiguration;

my $featureList = '';
foreach (@features) {
	$featureList .= qq(<option value="$_");
	$featureList .= qq( selected="yes") if ($_ eq $feature);
	$featureList .= qq(> $_ </option>\n\t\t\t\t\t);
}

my $content = '';

my $glyphList = '';
foreach (@glyphs) {
	$glyphList .= qq(<option value="$_");
	$glyphList .= qq( selected="yes") if ($_ eq $glyph);
	$glyphList .= qq(> $_ </option>\n\t\t\t\t\t);
}

my $trackList = '';
foreach (sort keys %tracks) {
	$trackList .= qq(<option value="$_");
	$trackList .= qq( selected="yes") if ($_ eq $track);
	$trackList .= qq(> $tracks{$_} </option>\n\t\t\t\t\t);
}
my $configuredTrackCount = $trackData->configuredTrackCount;

my $trackDetails = '';

if ($configuredTrackCount > 0) {
	unless ($track eq '') {
		$trackDetails .= qq(Track Configuration for \"$feature\" \n\n);
		$trackDetails .= qq(Glyph: ${${$curTrack{'glyph'}}[0]}{'glyph'} \n);
		foreach (@{$curTrack{'glyph'}}) {
			foreach (@{${$_}{'sub'}}) {
				my $ignoreIfNull = '';
				$ignoreIfNull = ${$_}{'IGNORE_IF_NULL'} if (${$_}{'IGNORE_IF_NULL'});
				if ($ignoreIfNull eq '1') {
					next if (${$_}{'VALUE'} eq '');
				}
				$trackDetails .= qq(${$_}{'CONF_TAG'}: );
				my $template = '';
				$template = ${$_}{'templ'} if (${$_}{'templ'});
				if ($template eq 'check') {
					if (${$_}{'VALUE'}) {
						if (${$_}{'VALUE'} eq (${$_}{'NAME'}) . '1') {
							$trackDetails .= qq(1 \n);
						} else {
							$trackDetails .= qq(0 \n);
						}
					} else {
						$trackDetails .= qq(0 \n);
					}
				} else {
					$trackDetails .= qq(${$_}{'VALUE'} \n);
				}
			}
		}
	}
}

$content .= qq( 
	<form class="uniForm inlineLabels deep" method="post" name="configureTracksAddForm"> 
		<p align="right">
			<input type="submit" disabled="yes" class="submitButton deep" name="$paramPostBackCommand" value="$saveLabel" />
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		</p>
		<fieldset class="inlineLabels deep">
			<legend class="deep">Describe your dataset</legend>
			<div class="ctrlHolder deep">
				<label class="deep">Description *</label>
				<p class="intro deep">Description appears in the popup menu that allows users to select the data source and in the header of the page.</p>
				<input type="text" name="$paramDescription" size="60" value="$description" disabled="yes" class="deep" />
				<p class="formHint deep">Description of the database</p>
			</div>
		</fieldset>

		<fieldset class="inlineLabels deep"> 
			<legend class="deep">Add New Track</legend> 
			<div class="ctrlHolder deep"> 
				<p class="intro deep">Add a new track by associating the feature to be displayed with the glyph of your choice. Click <input type="button" disabled="yes" class="demoButton deep" value="$addLabel" /> after selecting a feature from the list on the left and a glyph from the drop down list on the right to add the new track.</p>
				<table border="0" width="100%">
					<tr>
						<td width="25%" valign="top">
							<label class="complex deep">Feature * </label>
							<select name="$paramFeature" size="10" disabled="yes" class="complex deep">
								$featureList
							</select>
						</td>
						<td width="25%" valign="top">
							<label class="complex deep">Glyph </label> 
							<select name="$paramGlyph" size="1" disabled="yes" class="complex deep">
								$glyphList
							</select>
							<br><br>
							<textarea rows="5" cols="80" readonly="yes" name="txtGlyphDescription" disabled="yes" class="subComplex subDeep">);

							unless ($glyph eq '') {
								my $glyphDesc = $trackData->getGlyphDescription($glyph);
								$glyphDesc =~ s/\\\'/\'/g;
								$content .= $glyphDesc;
							}

							$content .= qq(</textarea>
						</td>
						<td width="50%" valign="top">);
							
							unless ($glyph eq '') {
								$content .= qq(<img src="/include/img/glyphs/$glyph.jpg" name="imgGlyph" />);
							}
							
							$content .= qq(&nbsp;
						</td>
					</tr>
				</table>
				<p class="formHint deep">Select a feature you want to configure and a glyph to apply to the selected feature</p> 
			</div>
			<div class="buttonPanel deep">
				<input type="submit" disabled="yes" class="submitButton deep" name="$paramPostBackCommand" value="$addLabel" /> 
			</div>
		</fieldset>
);

if ($configuredTrackCount > 0) {
	$content .= qq(
		<fieldset class="inlineLabels deep">
			<legend class="deep">Tracks Added</legend>
			<div class="ctrlHolder deep">
				<p class="intro deep">Select a track from the list on the left and you will see the configuration settings for that feature in the box on the right. Click on <input type="button" disabled="yes" class="demoButton deep" value="$editLabel" /> to edit the configuration settings of the selected track. In case you want to delete the selected track, click <input type="button" disabled="yes" class="demoButton deep" value="$deleteLabel" />. Once you are done adding tracks, you can proceed to the actual GBrowse display by clicking on <input type="button" disabled="yes" class="demoButton deep" value="$doneLabel" />. You will be allowed to come back and make further changes if desired.</p>
				<table border="0" width="100%">
					<tr>
						<td width="40%" valign="top">
							<label class="complex deep">Configured Tracks * </label>
							<select name="$paramTrack" size="10" disabled="yes" class="complex deep">
								$trackList
							</select>
						</td>
						<td width="60%" valign="top">
							<label class="complex deep">Configuration Settings </label>
							<textarea rows="10" cols="80" readonly="yes" name="txtTrackDetails" disabled="yes" class="complex deep">$trackDetails</textarea>
						</td>
					</tr>
				</table>
				<p class="formHint deep">The list of all the tracks added</p>
			</div>
			<div class="buttonPanel deep">
				<input type="submit" disabled="yes" class="submitButton deep" name="$paramPostBackCommand" value="$editLabel" />
				&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
				<input type="submit" disabled="yes" class="submitButton deep" name="$paramPostBackCommand" value="$deleteLabel" />
				&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
	);
	$content .= qq(
				<input type="submit" disabled="yes" class="submitButton deep" name="$paramPostBackCommand" value="$doneLabel" />
	);
	$content .= qq(
			</div>
		</fieldset>
	);
}
$content .= qq(
	</form>
);

$content .= qq(<div id="glyphForm">);
$content .= $Form->get;
$content .= qq(</div>);

print getStartHtml($q); 
print getContent($content);
print $q->end_html();

