#!/usr/bin/perl

use warnings;
use strict;

use lib '../lib';
use WebGB;
use CGI qw(:standard);

my $q = new CGI;
my $timeStampDigest = $q->url_param('tsd');
if ($timeStampDigest eq '') {
	print $q->redirect(
		-location => '/'
	);
	exit(0);
}

my $confFile =  $WebGB::CONF . '/gbrowse.conf/' . $timeStampDigest . '.conf'; 
open CONF, "<", $confFile or die "Can not open the specified file";
my @confContent = <CONF>;
close CONF;
for (my $i = 0; $i < scalar @confContent; $i++) {
	if ($confContent[$i] =~ /#WEBGB#$/) {
		splice(@confContent, $i, 1);
		$i--;
	}
}
print "Content-Type:text/x-download\n";
print "Content-Disposition:attachment;filename=$timeStampDigest.conf\n\n";
print @confContent;
exit(0);

