#!/usr/bin/perl

use warnings;
use strict;

use lib '../lib';
use CGI qw(:standard);
use WebGB;

my $q = new CGI;
my $timeStampDigest = $q->url_param('tsd');
if ($timeStampDigest eq '') {
	print $q->redirect(
		-location => '/'
	);
	exit(0);
}

my $content = '';
$content .= qq(
	<p align="justify">
		Your configuration is saved. You can continue at a later time from where you left by clicking on the link below. For your convenience, this link is also being sent to your email.
	</p>
	<p>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="http://$ENV{SERVER_NAME}/cgi-bin/configureTracks?tsd=$timeStampDigest">
			http://$ENV{SERVER_NAME}/cgi-bin/configureTracks?tsd=$timeStampDigest
		</a>
	</p>
	<p align="justify">
		If you have any questions or suggestions, please contact biohelp\@cgb.indiana.edu. Thanks for using WebGBrowse.
	</p>
	<p>
		<br>
		WebGBrowse Development Team<br>
		Center for Genomics and Bioinformatics<br>
		Indiana University<br>
	</p>
);

print getStartHtml($q); 
print getContent($content);
print $q->end_html();

